Repository codestates-seb/seb40_main_002, pull requests merged in 2022-12, with the labels that each got.

#109 feat : 예약페이지 페이지네이션 완료, 인터셉터 변경 완료
  client/src/api/index.ts
  client/src/components/GhAdmin/GhAdminList.tsx
  client/src/components/MyPage/UserInfoCard/UserInfoEdit.tsx
  client/src/components/common/GuesthouseCard.tsx
  client/src/components/common/Heart.tsx
  client/src/components/common/Nav/UserIconModal.tsx
  client/src/pages/GhAdminPage.tsx
Labels: ⛲ Feature, ⭐️ FE

#110 리뷰 페이지
  client/package-lock.json
  client/src/App.tsx
  client/src/apis/getGhInfo.ts
  client/src/apis/getGhReviewData.ts
  client/src/apis/getUserInfo.ts
  client/src/components/GhDetail/GhDetailComment.tsx
  client/src/components/common/Comment/DetailReview.tsx
  client/src/components/common/Comment/EditReply.tsx
  client/src/pages/GuestHouseDetail.tsx
  client/src/pages/ReviewPage.tsx
  client/src/types/ghDetailData.d.ts
Labels: ⛲ Feature, ⭐️ FE

#121 구글로그인 추가
  client/src/pages/Register.tsx
Labels: ⛲ Feature, ⭐️ FE

#122 🐛 fix : covnerURL 경로 수정
  client/src/pages/Register.tsx
Labels: 🚨 BugFix, ⭐️ FE

#123 ✨ feat : naver, google 이미지 proxy 추가
  client/src/setupProxy.js
Labels: 🚨 BugFix, ⭐️ FE

#125 🚑 hotfix : converURL 경로 수정
  client/src/pages/Register.tsx
Labels: 🚨 BugFix, ⭐️ FE

#132 🐛 fix : 이미지 파일 업로드 방식 수정
  client/src/pages/Register.tsx
Labels: 🚨 BugFix, ⭐️ FE

#133 ✨ feat : proxy source 추가
  client/src/pages/Register.tsx
  client/vercel.json
Labels: 🚨 BugFix, ⭐️ FE

#134 🐛 fix : convertURL 경로 수정
  client/src/pages/Register.tsx
Labels: 🚨 BugFix, ⭐️ FE

#135 ✅ test : 테스트용
  client/src/pages/Register.tsx
Labels: 🚨 BugFix, ✅ Test, ⭐️ FE

#136 🐛 fix : 프록시 경로 수정
  client/vercel.json
Labels: 🚨 BugFix, ⭐️ FE

#137 ✅ test : 테스트용
  client/src/pages/Register.tsx
Labels: 🚨 BugFix, ✅ Test, ⭐️ FE

#148 💄 style : 스타일 수정
  client/src/components/common/Footer.tsx
  client/tailwind.config.js
Labels: 🖼 HTML&CSS, ⭐️ FE

#151 💄 style : 폰트 색상 변경
  client/src/components/common/Footer.tsx
Labels: 🖼 HTML&CSS, ⭐️ FE

#152 💄 style : 스타일 수정
  client/src/components/common/Footer.tsx
Labels: 🖼 HTML&CSS, ⭐️ FE

#153 💄 style : footer, nav 스타일 수정
  client/src/components/common/Footer.tsx
  client/src/components/common/Navbar.tsx
Labels: 🖼 HTML&CSS, ⭐️ FE

#154 💄 style : footer 스타일 수정
  client/public/index.html
  client/src/components/common/Footer.tsx
Labels: 🖼 HTML&CSS, ⭐️ FE
