Repository codestates-seb/seb40_main_002, pull requests merged in 2022-11, with the labels that each got.

#13 Feat/ghcomponents
  client/package-lock.json
  client/package.json
  client/src/assets/img/roomSample.jpg
  client/src/components/common/Heart.tsx
  client/src/components/common/RoomInfo/Info.tsx
  client/src/components/common/RoomInfo/RoomInfo.tsx
  client/src/types/guesthouse.d.ts
  client/tailwind.config.js
Labels: ⛲ Feature, ⭐️ FE

#14 ✨Feat/navbar
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/Nav/DatePicker.tsx
  client/src/components/common/Nav/Keyword_input.tsx
  client/src/components/common/Nav/Location.tsx
  client/src/components/common/Nav/Logo.tsx
  client/src/components/common/Nav/Search.tsx
  client/src/components/common/Nav/SelectLocation.tsx
  client/src/components/common/Nav/UserIcon.tsx
  client/src/components/common/Nav/UserIconModal.tsx
  client/src/components/common/Nav/index.tsx
  client/src/components/common/Navbar.tsx
  client/src/components/common/Tag.tsx
  client/src/components/common/TagSelectModal/TagSelect.tsx
  client/src/components/common/TagSelectModal/TagSelectModal.tsx
  client/src/components/common/index.tsx
Labels: ⛲ Feature, ⭐️ FE

#15 ✨Feat : 후기 + 내역 관련 컴포넌트 제작
  client/src/assets/img/525tangerine_100729.png
  client/src/components/common/Comment/BottomLabel.tsx
  client/src/components/common/Comment/Comment.tsx
  client/src/components/common/Comment/DetailReview.tsx
  client/src/components/common/Comment/Details.tsx
  client/src/components/common/Comment/EditReply.tsx
  client/src/components/common/Comment/Sample.tsx
  client/src/components/common/Comment/StarRating.tsx
  client/src/components/common/Comment/TopLabel.tsx
  client/tailwind.config.js
Labels: ⛲ Feature, ⭐️ FE

#17 ✨ feat: reservation complete
  client/package-lock.json
  client/src/assets/img/arrowLeft.png
  client/src/assets/img/arrowRight.png
  client/src/components/common/Carousel/Carousel.tsx
  client/src/components/common/Carousel/CarouselBtn.tsx
  client/src/components/common/Carousel/CarouselDot.tsx
  client/src/components/common/ReservationInfo.tsx
  client/src/pages/Reservation.tsx
Labels: ⛲ Feature, ⭐️ FE

#18 ✨ Feat/ghcomponents: 대문, 로그인페이지, 편의시설 컴포넌트
  client/package-lock.json
  client/package.json
  client/src/assets/img/jeju.jpg
  client/src/components/Login/LoginButton.tsx
  client/src/components/common/Checkbox.tsx
  client/src/components/common/Facilities.tsx
  client/src/components/common/TagSelectModal/TagSelectButton.tsx
  client/src/hooks/useModal.ts
  client/src/pages/Door.tsx
  client/src/pages/Login.tsx
Labels: ⛲ Feature, ⭐️ FE

#23 ✨ feat:image preview / address
  client/package-lock.json
  client/package.json
  client/src/components/ReservationInfo/ReservationInfo.tsx
  client/src/components/Temporary/Address.tsx
  client/src/components/Temporary/ImagePreviewTset.tsx
  client/src/components/common/Carousel/CarouselBtn.tsx
  client/src/pages/Reservation.tsx
Labels: ⛲ Feature, ⭐️ FE

#28 ✨ feat: 결제페이지 제작 완료
  client/src/App.tsx
  client/src/components/common/Checkbox.tsx
  client/src/components/common/Footer.tsx
  client/src/components/common/Navbar.tsx
  client/src/components/paymentPage/GhInfo.tsx
  client/src/components/paymentPage/GhpayInfo.tsx
  client/src/components/paymentPage/PaymentContainer.tsx
  client/src/components/paymentPage/PaymentLeft.tsx
  client/src/components/paymentPage/PaymentRight.tsx
  client/src/components/paymentPage/ReservationContainer.tsx
  client/src/libs/dateCheck.ts
  client/src/pages/PaymentPage.tsx
  client/src/types/payment.d.ts
Labels: ⛲ Feature, ⭐️ FE

#33 ✨ feat: 숙소 등록 페이지 1차 pr + 숙소 상세 options map 로직 검증
  client/src/components/common/Checkbox.tsx
  client/src/components/common/Facilities.tsx
  client/src/components/common/FacilitiesArray.tsx
  client/src/components/ghEdit/FacilitiesContainer.tsx
  client/src/components/ghEdit/GhDescription.tsx
  client/src/pages/GhEditpage.tsx
Labels: ⭐️ FE

#41 ✨ feat:Gh Detail
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/GhDetail/GhAsk.tsx
  client/src/components/GhDetail/GhDetailComment.tsx
  client/src/components/GhDetail/GhDetailFacilities.tsx
  client/src/components/GhDetail/GhInfomation.tsx
  client/src/components/GhDetail/GhLocation.tsx
  client/src/components/GhDetail/GhReservation.tsx
  client/src/components/GhDetail/MapContainer.tsx
  client/src/components/GhDetail/ReservationPiker.tsx
  client/src/components/GhDetail/RoomsDetail.tsx
  client/src/components/common/Carousel/Carousel.tsx
  client/src/components/common/RoomInfo/RoomInfo.tsx
  client/src/pages/GusetHouseDetail.tsx
  client/tsconfig.json
Labels: ⛲ Feature, ⭐️ FE

#48 Feat/review page
  client/package-lock.json
  client/src/App.tsx
  client/src/components/common/Comment/DetailReview.tsx
  client/src/components/common/Comment/EditReply.tsx
  client/src/components/common/Comment/Sample.tsx
  client/src/components/common/Nav/SelectLocation.tsx
  client/src/pages/ReviewPage.tsx
Labels: ⛲ Feature, ⭐️ FE

#49 ✨ feat : 숙소 등록 1차 완성 + Proxy 세팅 완료 + roomInfo 수정
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/Temporary/Address.tsx
  client/src/components/common/Navbar.tsx
  client/src/components/common/RoomInfo/RoomInfo.tsx
  client/src/components/common/TagSelectModal/TagSelect.tsx
  client/src/components/common/TagSelectModal/TagSelectButton.tsx
  client/src/components/ghEdit/AddressContainer.tsx
  client/src/components/ghEdit/AddressInput.tsx
  client/src/components/ghEdit/FacilitiesContainer.tsx
  client/src/components/ghEdit/GhDescription.tsx
  client/src/components/ghEdit/Ghname.tsx
  client/src/components/ghEdit/ImageContainer.tsx
  client/src/components/ghEdit/InputContainer.tsx
  client/src/components/ghEdit/Messenger.tsx
  client/src/components/ghEdit/RoomEdit.tsx
  client/src/components/ghEdit/RoomEditer.tsx
  client/src/components/ghEdit/TagContainer.tsx
  client/src/libs/srcToFile.ts
  client/src/pages/GhEditpage.tsx
  client/src/setupProxy.js
  client/src/types/guesthouse.d.ts
  client/tsconfig.json
Labels: ⛲ Feature, ⭐️ FE

#54 ✨ feat/ghcomponents: 메인페이지, 검색 결과 페이지 수정, 마이페이지 구현
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Login/LoginButton.tsx
  client/src/components/Main/GuesthouseList.tsx
  client/src/components/Main/SortButton.tsx
  client/src/components/MyPage/MyPageTabs/HeartTab.tsx
  client/src/components/MyPage/MyPageTabs/MyPageTabs.tsx
  client/src/components/MyPage/MyPageTabs/ReservationTab.tsx
  client/src/components/MyPage/MyPageTabs/ReviewTab.tsx
  client/src/components/MyPage/UserInfoCard/UserInfo.tsx
  client/src/components/MyPage/UserInfoCard/UserInfoCard.tsx
  client/src/components/MyPage/UserInfoCard/UserInfoEdit.tsx
  client/src/hooks/useInfiniteScroll.ts
  client/src/pages/Main.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SearchResult.tsx
  client/src/types/community.d.ts
  client/src/types/guesthouse.d.ts
  client/src/types/user.d.ts
Labels: ⛲ Feature, ⭐️ FE

#75 ✨feat : 회원가입
  client/src/App.tsx
  client/src/components/Login/LoginButton.tsx
  client/src/components/Register/Birthday.tsx
  client/src/components/Register/RadioBtn.tsx
  client/src/components/Register/RightSide.tsx
  client/src/components/Register/UserImg.tsx
  client/src/components/common/DuplicateBtn.tsx
  client/src/components/common/Input.tsx
  client/src/components/common/Nav/Logo.tsx
  client/src/components/common/Nav/SelectLocation.tsx
  client/src/components/common/Nav/UserIconModal.tsx
  client/src/libs/getuserParams.ts
  client/src/pages/Register.tsx
  client/src/pages/UserData.tsx
  client/src/setupProxy.js
Labels: ⛲ Feature, ⭐️ FE

#84 🐛 fix : comment 관련 수정 완료
  client/src/components/common/Comment/BottomLabel.tsx
  client/src/components/common/Comment/Comment.tsx
  client/src/components/common/Comment/DetailReview.tsx
  client/src/components/common/Comment/Details.tsx
  client/src/components/common/Comment/EditReply.tsx
  client/src/components/common/Comment/MypageReview.tsx
  client/src/components/common/Comment/Sample.tsx
Labels: 🚨 BugFix, ⭐️ FE

#90 ✨ feat: 로그인, 리프레쉬 관련 인터셉터 axios 제작
  client/src/api/index.ts
  client/src/api/member.ts
  client/src/pages/GhEditPage2.tsx
  client/src/pages/Hostingpage.tsx
  client/src/setupProxy.js
Labels: ⛲ Feature, ⭐️ FE

#96 회원가입 (카카오, 네이버)
  client/src/components/Register/RightSide.tsx
  client/src/components/Register/UserImg.tsx
  client/src/components/common/Input.tsx
  client/src/pages/Register.tsx
Labels: ⛲ Feature, ⭐️ FE
